const products = [
  {
    id: 1,
    name: "Living Room Sets",
    price: 1520.0,
    oldPrice: 1540.0,
    imgSrc: "../../images/section3/img1.jpg",
    alt: "Living Room Set",
  },
  {
    id: 2,
    name: "Sofa for Living Room",
    price: 1520.0,
    oldPrice: 1540.0,
    imgSrc: "../../images/section3/img2.jpg",
    alt: "Sofa for Living Room",
    discount: "-15%",
  },
  {
    id: 3,
    name: "Living Room Sets",
    price: 1520.0,
    oldPrice: 1540.0,
    imgSrc: "../../images/section3/img3.jpg",
    alt: "Living Room Set",
    discount: "-10%",
  },
  {
    id: 4,
    name: "product with video",
    price: 1520.0,
    oldPrice: 1540.0,
    imgSrc: "../../images/section3/img4.jpg",
    alt: "Living Room Set",
  },
  {
    id: 5,
    name: "Unique content for each",
    price: 855.0,
    oldPrice: 1000.0,
    imgSrc: "../../images/section3/img5.jpg",
    alt: "Living Room Set",
    discount: "-11%",
  },
  {
    id: 6,
    name: "new badge product",
    price: 10.0,
    oldPrice: 154.0,
    imgSrc: "../../images/section3/img6.jpg",
    alt: "Living Room Set",
  },
  {
    id: 7,
    name: "variable product",
    price: 124.0,
    oldPrice: 1540.0,
    imgSrc: "../../images/section3/img7.jpg",
    alt: "Living Room Set",
    discount: "-18%",
  },
  {
    id: 8,
    name: "soldout product",
    price: 20.0,
    oldPrice: 200.0,
    imgSrc: "../../images/section3/img8.jpg",
    alt: "Living Room Set",
    discount: "-34%",
  },

  {
    id: 9,
    name: "Living Room Sets",
    price: 152.0,
    oldPrice: 154.0,
    imgSrc: "../../images/section3/img1.jpg",
    alt: "Living Room Set",
  },
  {
    id: 10,
    name: "Sofa for Living Room",
    price: 120.0,
    oldPrice: 140.0,
    imgSrc: "../../images/section3/img2.jpg",
    alt: "Sofa for Living Room",
    discount: "-15%",
  },
  {
    id: 11,
    name: "Living Room Sets",
    price: 150.0,
    oldPrice: 150.0,
    imgSrc: "../../images/section3/img3.jpg",
    alt: "Living Room Set",
    discount: "-10%",
  },
  {
    id: 12,
    name: "product with video",
    price: 520.0,
    oldPrice: 540.0,
    imgSrc: "../../images/section3/img4.jpg",
    alt: "Living Room Set",
  },
  {
    id: 13,
    name: "Unique content for each",
    price: 55.0,
    oldPrice: 100.0,
    imgSrc: "../../images/section3/img5.jpg",
    alt: "Living Room Set",
    discount: "-11%",
  },
  {
    id: 14,
    name: "new badge product",
    price: 10.0,
    oldPrice: 15.0,
    imgSrc: "../../images/section3/img6.jpg",
    alt: "Living Room Set",
  },
  {
    id: 15,
    name: "variable product",
    price: 124.0,
    oldPrice: 540.0,
    imgSrc: "../../images/section3/img7.jpg",
    alt: "Living Room Set",
    discount: "-18%",
  },
  {
    id: 16,
    name: "soldout product",
    price: 20.0,
    oldPrice: 200.0,
    imgSrc: "../../images/section3/img8.jpg",
    alt: "Living Room Set",
    discount: "-34%",
  },
  {
    id: 17,
    name: "Modern Living Room Set",
    price: 1520.0,
    oldPrice: 1540.0,
    imgSrc: "../../images/section3/img1.jpg",
    alt: "Living Room Set",
  },
  {
    id: 18,
    name: "Sofa for Living Room",
    price: 1300.0,
    oldPrice: 1500.0,
    imgSrc: "../../images/section3/img2.jpg",
    alt: "Sofa",
    discount: "-13%",
  },
  {
    id: 19,
    name: "Elegant Chair Set",
    price: 800.0,
    oldPrice: 1000.0,
    imgSrc: "../../images/section3/img3.jpg",
    alt: "Chair Set",
    discount: "-20%",
  },
  {
    id: 20,
    name: "Wooden Coffee Table",
    price: 300.0,
    oldPrice: 400.0,
    imgSrc: "../../images/section3/img4.jpg",
    alt: "Coffee Table",
    discount: "-25%",
  },
  {
    id: 5,
    name: "Luxury Sofa Set",
    price: 2200.0,
    oldPrice: 2500.0,
    imgSrc: "../../images/section3/img5.jpg",
    alt: "Luxury Sofa Set",
    discount: "-12%",
  },
  {
    id: 21,
    name: "Contemporary TV Unit",
    price: 500.0,
    oldPrice: 600.0,
    imgSrc: "../../images/section3/img6.jpg",
    alt: "TV Unit",
    discount: "-17%",
  },
  {
    id: 22,
    name: "Classic Recliner",
    price: 899.99,
    oldPrice: 1099.99,
    imgSrc: "../../images/section3/img7.jpg",
    alt: "Classic Recliner",
    discount: "-18%",
  },
  {
    id: 23,
    name: "Glass Center Table",
    price: 320.0,
    oldPrice: 450.0,
    imgSrc: "../../images/section3/img8.jpg",
    alt: "Glass Center Table",
    discount: "-29%",
  },
  {
    id: 24,
    name: "Leather Couch",
    price: 1780.0,
    oldPrice: 1980.0,
    imgSrc: "../../images/section3/img1.jpg",
    alt: "Leather Couch",
    discount: "-10%",
  },
  {
    id: 25,
    name: "Minimal Bookshelf",
    price: 250.0,
    oldPrice: 300.0,
    imgSrc: "../../images/section3/img2.jpg",
    alt: "Minimal Bookshelf",
    discount: "-17%",
  },
  {
    id: 26,
    name: "Wall Mounted Cabinet",
    price: 400.0,
    oldPrice: 520.0,
    imgSrc: "../../images/section3/img3.jpg",
    alt: "Wall Mounted Cabinet",
    discount: "-23%",
  },
  {
    id: 27,
    name: "Foldable Ottoman",
    price: 99.99,
    oldPrice: 150.0,
    imgSrc: "../../images/section3/img4.jpg",
    alt: "Foldable Ottoman",
    discount: "-33%",
  },
  {
    id: 28,
    name: "Compact Study Desk",
    price: 450.0,
    oldPrice: 520.0,
    imgSrc: "../../images/section3/img5.jpg",
    alt: "Compact Study Desk",
    discount: "-13%",
  },
  {
    id: 29,
    name: "Upholstered Bench",
    price: 310.0,
    oldPrice: 375.0,
    imgSrc: "../../images/section3/img6.jpg",
    alt: "Upholstered Bench",
    discount: "-17%",
  },
  {
    id: 30,
    name: "Accent Chair",
    price: 600.0,
    oldPrice: 700.0,
    imgSrc: "../../images/section3/img7.jpg",
    alt: "Accent Chair",
    discount: "-14%",
  },
  {
    id: 32,
    name: "Vintage Armchair",
    price: 620.0,
    oldPrice: 750.0,
    imgSrc: "../../images/section3/img8.jpg",
    alt: "Vintage Armchair",
    discount: "-17%",
  },
];

export default products;